name:                deepscite-hs
version:             0.1.2.0
synopsis:            DeepScite in Haskell using the Haskell TensorFlow bindings.
description:         Please see README.md
homepage:            https://github.com/silky/deep-scite/
license:             MIT
author:              Noon van der Silk
maintainer:          noonsilk@gmail.com
copyright:           Noon van der Silk
category:            Web


default-extensions:
    - UndecidableInstances

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - cassava
  - filepath
  - lens-family
  - mtl
  - proto-lens
  - random
  - random-extras
  - random-fu
  - random-source
  - rvar
  - tensorflow
  - tensorflow-logging
  - tensorflow-ops
  - tensorflow-core-ops == 0.1.*
  - tensorflow-proto    == 0.1.*
  - tensorflow-opgen    == 0.1.*
  - tensorflow-records
  - text
  - transformers
  - vector


executables:
  deepscite-hs:
    source-dirs:      src
    main:             Main.hs
