resolver: lts-8.15
flags: {}
extra-package-dbs: []
system-ghc: false


packages:
 - '.'
 - location: 
     git    : https://github.com/tensorflow/haskell/
     commit : afbcd1b7721e082211496c1be11fc3550bc205bc
   subdirs:
        - tensorflow
        - tensorflow-logging
        - tensorflow-ops
        - tensorflow-core-ops
        - tensorflow-proto
        - tensorflow-opgen
        - tensorflow-records
        - tensorflow-records-conduit
   extra-dep: true


extra-deps:
- snappy-framing-0.1.1
- snappy-0.2.0.2
- random-extras-0.19


# Allow our custom Setup.hs scripts to import Data.ProtoLens.Setup from the version of
# `proto-lens-protoc` in stack's local DB.  See:
# https://github.com/google/proto-lens/blob/master/README.md#using-cabal
explicit-setup-deps:
  "*": true
